# gold.edgar.filing_events
# Processes silver.edgar.form10_filings_rss via CDF to create filing events

config:
  mode: streaming
  streaming_trigger_mode:
    available_now: True
  checkpoint_path: s3://datsando-prod/dcf_valuation/checkpoints/gold/edgar/filing_events_v1

producer:
  variant: ReadTable
  parameters:
    table: silver.edgar.form10_filings_rss
    options:
      readChangeFeed: True
      startingVersion: $ENV{CDF_STARTING_VERSION:0}

operators:
  - variant: Filter
    parameters:
      condition: _change_type in ('insert', 'update_postimage')

  - variant: Filter
    parameters:
      condition: form_type in ('10-Q', '10-K', '10-QT')

  - variant: Select
    parameters:
      cols:
        - _id
        - cik
        - accession_number
        - filing_id
        - form_type
        - filed_date
        - link
        - updated as source_updated

consumer:
  variant: MergeTable
  parameters:
    table: gold.edgar.filing_events
    key_columns: [cik, accession_number]
