# gold.financials.statement_lines
# Joins silver.edgar.company_facts to gold.financials.tag_map
# Applies unit/duration filters and selects best candidate per key

config:
  mode: streaming
  streaming_defer_operators: True
  streaming_trigger_mode:
    available_now: True
  checkpoint_path: s3://datsando-prod/pipeline_equities/checkpoints/gold/financials/statement_lines_v4

producer:
  variant: ReadTable
  parameters:
    table: silver.edgar.company_facts
    options:
      readChangeFeed: True
      # Incremental mode - process only new changes from latest version
      startingVersion: $ENV{CDF_STARTING_VERSION:latest}

operators:
  - variant: Filter
    parameters:
      condition: _change_type in ('insert', 'update_postimage')

  # Join to tag_map to get line_item mappings
  - variant: ExecSQL
    parameters:
      sql_query: |
        with facts_with_mapping as (
          select
            cf._id,
            cf.cik,
            tm.line_item,
            cf.start as period_start,
            cf.end as period_end,
            cf.fy,
            cf.fp,
            cf.val,
            cf.unit_of_measure,
            cf.filed,
            cf.form,
            cf.accn,
            cf.frame,
            cf.tag as source_tag,
            cf.taxonomy as source_taxonomy,
            tm.priority,
            tm.is_flow,
            tm.unit_allowlist,
            tm.duration_months_allowlist,
            -- Calculate duration in months for flow items
            months_between(cf.end, cf.start) as duration_months
          from data cf
          inner join gold.financials.tag_map tm 
            on cf.taxonomy = tm.source_taxonomy 
            and cf.tag = tm.source_tag
        ),
        -- Apply unit allowlist filter
        filtered_by_unit as (
          select *
          from facts_with_mapping
          where unit_allowlist is null 
             or array_contains(unit_allowlist, unit_of_measure)
        ),
        -- Apply duration allowlist filter for flow items
        filtered_by_duration as (
          select *
          from filtered_by_unit
          where is_flow = false
             or duration_months_allowlist is null
             or array_contains(duration_months_allowlist, cast(duration_months as int))
        ),
        -- Rank candidates by priority, then filed desc, then accn desc
        ranked as (
          select
            *,
            row_number() over (
              partition by cik, line_item, period_end, fy, fp, unit_of_measure
              order by priority asc, filed desc, accn desc
            ) as selection_rank
          from filtered_by_duration
        )
        select
          _id,
          cik,
          line_item,
          period_start,
          period_end,
          fy,
          fp,
          val,
          unit_of_measure,
          filed,
          form,
          accn,
          frame,
          source_tag,
          source_taxonomy,
          selection_rank,
          false as is_restated  -- v1: restatement detection deferred
        from ranked
        where selection_rank = 1

consumer:
  variant: MergeTable
  parameters:
    table: gold.financials.statement_lines
    key_columns: [cik, line_item, period_end, fy, fp, unit_of_measure]
