# gold.edgar.filing_events_backfill
# One-time batch pipeline to populate filing_events from company_facts
# Extracts 10-Q/K filings from the last 5 years (~116K filings, ~6K CIKs)

config:
  mode: batch

producer:
  variant: ExecSQL
  parameters:
    sql_query: |
      with filings as (
        select
          cik,
          accn,
          form,
          filed,
          row_number() over (
            partition by cik, accn
            order by filed desc
          ) as rn
        from silver.edgar.company_facts
        where form in ('10-Q', '10-K', '10-QT')
          and filed >= '2020-01-01'
      ),
      deduped as (
        select cik, accn, form, filed
        from filings
        where rn = 1
      )
      select
        uuid() as _id,
        cik,
        accn as accession_number,
        cast(null as string) as filing_id,
        form as form_type,
        filed as filed_date,
        cast(null as string) as link,
        current_timestamp() as source_updated
      from deduped

consumer:
  variant: MergeTable
  parameters:
    table: gold.edgar.filing_events
    key_columns: [cik, accession_number]
