# gold.damodaran.ratings_spreads
# Loads Damodaran ratings spreads from seed CSV

config:
  mode: batch

producer:
  variant: ReadCSV
  parameters:
    path: $ASSET_PATH{pipeline_equities.assets, gold/seed/damodaran/ratings_spreads.csv}
    options:
      header: "true"
      inferSchema: "false"

operators:
  - variant: WithColumns
    parameters:
      cols_map:
        as_of_date: cast(as_of_date as date)
        default_spread: cast(default_spread as double)
        loaded_at: current_timestamp()

  - variant: Select
    parameters:
      cols:
        - as_of_date
        - rating
        - default_spread
        - loaded_at

consumer:
  variant: MergeTable
  parameters:
    table: gold.damodaran.ratings_spreads
    key_columns: [as_of_date, rating]
