# gold.damodaran.implied_erp
# Loads Damodaran implied ERP from seed CSV

config:
  mode: batch

producer:
  variant: ReadCSV
  parameters:
    path: $ASSET_PATH{dcf_valuation.assets, gold/seed/damodaran/implied_erp.csv}
    options:
      header: "true"
      inferSchema: "false"

operators:
  - variant: WithColumns
    parameters:
      cols_map:
        as_of_date: cast(as_of_date as date)
        implied_erp: cast(implied_erp as double)
        loaded_at: current_timestamp()

  - variant: Select
    parameters:
      cols:
        - as_of_date
        - implied_erp
        - source_url
        - loaded_at

consumer:
  variant: MergeTable
  parameters:
    table: gold.damodaran.implied_erp
    key_columns: [as_of_date]
