# gold.valuation.dcf_results
# Aggregates cashflows into final DCF valuation

config:
  mode: batch

producer:
  variant: ExecSQL
  parameters:
    sql_query: |
      with cashflow_sums as (
        select
          cik,
          valuation_date,
          assumption_set_id,
          source_accn,
          model_type,
          sum(case when not is_terminal then pv else 0 end) as pv_explicit,
          sum(case when is_terminal then pv else 0 end) as pv_terminal
        from gold.valuation.dcf_cashflows
        group by cik, valuation_date, assumption_set_id, source_accn, model_type
      ),
      with_inputs as (
        select
          cs.*,
          i.cash_latest,
          i.debt_st_latest,
          i.debt_lt_latest,
          i.shares_basic_latest,
          i.market_price,
          i.has_minimum_inputs,
          i.missing_fields
        from cashflow_sums cs
        inner join gold.valuation.dcf_inputs i
          on cs.cik = i.cik
          and cs.valuation_date = i.valuation_date
          and cs.assumption_set_id = i.assumption_set_id
          and cs.source_accn = i.source_accn
          and cs.model_type = i.model_type
      ),
      with_ev as (
        select
          wi.*,
          wi.pv_explicit + wi.pv_terminal as total_pv,
          -- Enterprise value (corporate track)
          case 
            when wi.model_type = 'corporate' then wi.pv_explicit + wi.pv_terminal
            else null
          end as enterprise_value,
          -- Equity value
          case 
            when wi.model_type = 'corporate' then
              (wi.pv_explicit + wi.pv_terminal) + coalesce(wi.cash_latest, 0) 
              - coalesce(wi.debt_st_latest, 0) - coalesce(wi.debt_lt_latest, 0)
            else
              wi.pv_explicit + wi.pv_terminal
          end as equity_value
        from with_inputs wi
      ),
      final as (
        select
          we.cik,
          we.valuation_date,
          we.assumption_set_id,
          we.source_accn,
          we.model_type,
          we.pv_explicit,
          we.pv_terminal,
          we.enterprise_value,
          we.equity_value,
          -- Value per share
          case 
            when we.shares_basic_latest > 0 then we.equity_value / we.shares_basic_latest
            else null
          end as value_per_share,
          -- Terminal percentage
          case 
            when we.total_pv > 0 then we.pv_terminal / we.total_pv
            else null
          end as terminal_pct,
          -- Upside/downside vs market
          case 
            when we.market_price > 0 and we.shares_basic_latest > 0 then
              (we.equity_value / we.shares_basic_latest - we.market_price) / we.market_price
            else null
          end as upside_downside,
          we.has_minimum_inputs,
          we.missing_fields
        from with_ev we
      )
      select * from final

consumer:
  variant: MergeTable
  parameters:
    table: gold.valuation.dcf_results
    key_columns: [cik, valuation_date, assumption_set_id, source_accn, model_type]
