# gold.valuation.assumption_sets
# Seeds default DCF assumption sets

config:
  mode: batch

producer:
  variant: ExecSQL
  parameters:
    sql_query: |
      select * from values
        (
          'damodaran_v1',
          10,
          'linear',
          'rf',
          'roic_to_wacc',
          'effective_to_marginal_linear',
          0.25,
          'target_de_ratio'
        ),
        (
          'damodaran_v1_conservative',
          10,
          'linear',
          'min_rf_3pct',
          'roic_to_wacc',
          'effective_to_marginal_linear',
          0.25,
          'target_de_ratio'
        )
      as t(
        assumption_set_id,
        fade_years,
        growth_fade_shape,
        terminal_growth_method,
        terminal_roic_policy,
        tax_policy,
        marginal_tax_rate,
        wacc_weight_method
      )

consumer:
  variant: MergeTable
  parameters:
    table: gold.valuation.assumption_sets
    key_columns: [assumption_set_id]
