# gold.damodaran.synthetic_rating_bands
# Loads Damodaran synthetic rating bands from seed CSV

config:
  mode: batch

producer:
  variant: ReadCSV
  parameters:
    path: $ASSET_PATH{dcf_valuation.assets, gold/seed/damodaran/synthetic_rating_bands.csv}
    options:
      header: "true"
      inferSchema: "false"

operators:
  - variant: WithColumns
    parameters:
      cols_map:
        min_interest_coverage: cast(min_interest_coverage as double)
        max_interest_coverage: cast(max_interest_coverage as double)
        loaded_at: current_timestamp()

  - variant: Select
    parameters:
      cols:
        - rating
        - min_interest_coverage
        - max_interest_coverage
        - loaded_at

consumer:
  variant: MergeTable
  parameters:
    table: gold.damodaran.synthetic_rating_bands
    key_columns: [rating]
