config:
  mode: streaming
  streaming_defer_operators: True
  streaming_trigger_mode:
    available_now: True
  checkpoint_path: s3://datsando-prod/dcf_valuation/checkpoints/bronze/edgar/company_facts_v1

producer:
  variant: ReadTable
  parameters:
    table: silver.edgar.form10_filings_rss
    options:
      readChangeFeed: True
      startingVersion: 6

operators:
  - variant: Filter
    parameters:
      condition: _change_type = 'insert' and form_type in ('10-K', '10-Q', '10-QT')

  - variant: RESTOperator
    parameters:
      url: https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json
      method: GET
      source_col: cik
      param_name_for_value: cik
      param_location: path
      ignore_error_codes: [404]
      headers:
        User-Agent: "Datsando datsando@outlook.com"

  - variant: Select
    parameters:
      cols:
        - _id
        - cik
        - accession_number
        - content

  - variant: Filter
    parameters:
      condition: content is not null

consumer:
  variant: MergeTable
  parameters:
    table: bronze.edgar.company_facts
    key_columns: [cik, accession_number]
