# gold.financials.flow_ttm
# Computes trailing 12-month sums from quarterly flow values

config:
  mode: batch

producer:
  variant: ExecSQL
  parameters:
    sql_query: |
      with quarterly_with_row as (
        select
          cik,
          line_item,
          fiscal_quarter_end,
          quarter_val,
          row_number() over (
            partition by cik, line_item 
            order by fiscal_quarter_end
          ) as rn
        from gold.financials.flow_quarterly
        where quarter_val is not null
      ),
      ttm_calc as (
        select
          q.cik,
          q.line_item,
          q.fiscal_quarter_end as as_of_period_end,
          sum(q2.quarter_val) as ttm_val,
          count(q2.quarter_val) as quarters_in_ttm
        from quarterly_with_row q
        inner join quarterly_with_row q2
          on q.cik = q2.cik
          and q.line_item = q2.line_item
          and q2.fiscal_quarter_end > add_months(q.fiscal_quarter_end, -12)
          and q2.fiscal_quarter_end <= q.fiscal_quarter_end
        group by q.cik, q.line_item, q.fiscal_quarter_end
      )
      select
        cik,
        line_item,
        as_of_period_end,
        ttm_val,
        quarters_in_ttm
      from ttm_calc

consumer:
  variant: MergeTable
  parameters:
    table: gold.financials.flow_ttm
    key_columns: [cik, line_item, as_of_period_end]
