# gold.financials.balance_quarterly
# Extracts point-in-time stock (balance sheet) items

config:
  mode: batch

producer:
  variant: ExecSQL
  parameters:
    sql_query: |
      with stock_items as (
        -- Get only stock (non-flow) line items from tag_map
        select distinct line_item
        from gold.financials.tag_map
        where is_flow = false
      ),
      statement_stocks as (
        select
          sl.cik,
          sl.line_item,
          sl.period_end,
          sl.val,
          sl.filed,
          sl.accn,
          row_number() over (
            partition by sl.cik, sl.line_item, sl.period_end
            order by sl.filed desc, sl.accn desc
          ) as rn
        from gold.financials.statement_lines sl
        inner join stock_items si on sl.line_item = si.line_item
        where sl.unit_of_measure = 'USD'
      )
      select
        cik,
        line_item,
        period_end,
        val,
        filed,
        accn
      from statement_stocks
      where rn = 1

consumer:
  variant: MergeTable
  parameters:
    table: gold.financials.balance_quarterly
    key_columns: [cik, line_item, period_end]
