# gold.dim.sic_to_damodaran_industry
# Loads SIC to Damodaran industry mapping from seed CSV

config:
  mode: batch

producer:
  variant: ReadCSV
  parameters:
    path: $ASSET_PATH{dcf_valuation.assets, gold/seed/dim/sic_to_damodaran_industry.csv}
    options:
      header: "true"
      inferSchema: "false"

operators:
  - variant: WithColumns
    parameters:
      cols_map:
        sic: cast(sic as int)
        loaded_at: current_timestamp()

  - variant: Select
    parameters:
      cols:
        - sic
        - damodaran_industry
        - mapping_version
        - loaded_at

consumer:
  variant: MergeTable
  parameters:
    table: gold.dim.sic_to_damodaran_industry
    key_columns: [sic]
