# gold.financials.working_capital
# Computes non-cash working capital and YoY changes

config:
  mode: batch

producer:
  variant: ExecSQL
  parameters:
    sql_query: |
      with balance_pivot as (
        select
          cik,
          period_end as as_of_period_end,
          max(case when line_item = 'current_assets' then val end) as current_assets,
          max(case when line_item = 'cash' then val end) as cash,
          max(case when line_item = 'current_liabilities' then val end) as current_liabilities,
          max(case when line_item = 'debt_st' then val end) as debt_st
        from gold.financials.balance_quarterly
        where line_item in ('current_assets', 'cash', 'current_liabilities', 'debt_st')
        group by cik, period_end
      ),
      with_nwc as (
        select
          cik,
          as_of_period_end,
          current_assets,
          cash,
          current_liabilities,
          debt_st,
          -- Non-cash WC = (Current Assets - Cash) - (Current Liabilities - Short-term Debt)
          coalesce(current_assets, 0) - coalesce(cash, 0) 
            - (coalesce(current_liabilities, 0) - coalesce(debt_st, 0)) as non_cash_working_capital,
          -- Quality flags for missing components
          array_compact(array(
            case when current_assets is null then 'missing_current_assets' end,
            case when cash is null then 'missing_cash' end,
            case when current_liabilities is null then 'missing_current_liabilities' end,
            case when debt_st is null then 'missing_debt_st' end
          )) as quality_flags_base
        from balance_pivot
      ),
      with_yoy as (
        select
          curr.cik,
          curr.as_of_period_end,
          curr.current_assets,
          curr.cash,
          curr.current_liabilities,
          curr.debt_st,
          curr.non_cash_working_capital,
          curr.non_cash_working_capital - prior.non_cash_working_capital as non_cash_working_capital_yoy_change,
          case 
            when prior.non_cash_working_capital is null then 
              array_union(curr.quality_flags_base, array('missing_prior_year_wc'))
            else curr.quality_flags_base
          end as quality_flags
        from with_nwc curr
        left join with_nwc prior
          on curr.cik = prior.cik
          and prior.as_of_period_end = add_months(curr.as_of_period_end, -12)
      )
      select
        cik,
        as_of_period_end,
        current_assets,
        cash,
        current_liabilities,
        debt_st,
        non_cash_working_capital,
        non_cash_working_capital_yoy_change,
        quality_flags
      from with_yoy

consumer:
  variant: MergeTable
  parameters:
    table: gold.financials.working_capital
    key_columns: [cik, as_of_period_end]
