config:
  mode: streaming
  streaming_trigger_mode:
    available_now: True
  checkpoint_path: s3://datsando-prod/dcf_valuation/checkpoints/silver/fred/market_yield_10yr_v1

producer:
  variant: ReadTable
  parameters:
    table: bronze.fred.series_observations

operators:
  - variant: Filter
    parameters:
      condition: value is not null

  - variant: Select
    parameters:
      cols:
        - _id
        - observation_date
        - value as percent

consumer:
  variant: MergeTable
  parameters:
    key_columns:
      - observation_date
    table: silver.fred.market_yield_10yr
