config:
  mode: batch

producer:
  variant: RESTProducer
  parameters:
    url: https://api.massive.com/v2/snapshot/locale/us/markets/stocks/tickers
    method: GET
    api_key_secret:
      scope: pipeline_equities
      key: massive.api_key
    next_page_key: next_url

operators:
  - variant: WithColumns
    parameters:
      cols_map:
        extracted: get_json_object(headers, '$.Date')
        cleaned: regexp_replace(extracted, '^[A-Za-z]{3}, ', '')

  - variant: Select
    parameters:
      cols:
        - cast(from_utc_timestamp(current_timestamp(), 'America/New_York') as date) as snapshot_date
        - to_timestamp(cleaned, 'dd MMM yyyy HH:mm:ss z') as access_ts
        - headers
        - content


consumer:
  variant: MergeTable
  parameters:
    key_columns: [snapshot_date]
    table: bronze.massive.snapshot_all_tickers
