# gold.dim.company
# Derives company dimension with SIC codes from SEC submissions API
# Determines is_financial based on SIC codes (6000-6999 = financial)

config:
  mode: batch

producer:
  variant: ExecSQL
  parameters:
    sql_query: |
      with latest_facts as (
        select
          cik,
          max(filed) as latest_filed
        from silver.edgar.company_facts
        where taxonomy = 'dei' and tag = 'EntityRegistrantName'
        group by cik
      ),
      entity_names as (
        select
          cf.cik,
          first(cf.val) as entity_name
        from silver.edgar.company_facts cf
        inner join latest_facts lf on cf.cik = lf.cik and cf.filed = lf.latest_filed
        where cf.taxonomy = 'dei' and cf.tag = 'EntityRegistrantName'
        group by cf.cik
      ),
      -- Get SIC and metadata from SEC submissions API
      sic_data as (
        select
          cik,
          try_cast(nullif(sic, '') as int) as sic,
          sic_description,
          entity_name as sec_entity_name,
          fiscal_year_end,
          state_of_incorporation,
          category
        from bronze.sec.company_submissions
      )
      select
        en.cik,
        coalesce(sd.sec_entity_name, en.entity_name) as entity_name,
        sd.sic,
        sd.sic_description,
        case 
          when sd.sic >= 6000 and sd.sic < 7000 then true
          else false
        end as is_financial,
        case
          when sd.sic >= 6000 and sd.sic < 6100 then 'depository'
          when sd.sic >= 6100 and sd.sic < 6200 then 'nondepository_credit'
          when sd.sic >= 6200 and sd.sic < 6300 then 'securities_commodities'
          when sd.sic >= 6300 and sd.sic < 6400 then 'insurance_carriers'
          when sd.sic >= 6400 and sd.sic < 6500 then 'insurance_agents'
          when sd.sic >= 6500 and sd.sic < 6600 then 'real_estate'
          when sd.sic >= 6700 and sd.sic < 7000 then 'holding_investment'
          else null
        end as financial_class,
        sd.fiscal_year_end,
        sd.state_of_incorporation,
        sd.category
      from entity_names en
      left join sic_data sd on en.cik = sd.cik

consumer:
  variant: MergeTable
  parameters:
    table: gold.dim.company
    key_columns: [cik]
