# gold.dim.company
# Derives company dimension from silver.edgar.company_facts (companyfacts headers)
# Determines is_financial based on SIC codes (6000-6999 = financial)

config:
  mode: batch

producer:
  variant: ExecSQL
  parameters:
    sql_query: |
      with latest_facts as (
        select
          cik,
          max(filed) as latest_filed
        from silver.edgar.company_facts
        where taxonomy = 'dei' and tag = 'EntityRegistrantName'
        group by cik
      ),
      entity_names as (
        select
          cf.cik,
          first(cf.val) as entity_name
        from silver.edgar.company_facts cf
        inner join latest_facts lf on cf.cik = lf.cik and cf.filed = lf.latest_filed
        where cf.taxonomy = 'dei' and cf.tag = 'EntityRegistrantName'
        group by cf.cik
      ),
      sic_codes as (
        -- Get SIC from SEC RSS feed titles or derive from company name patterns
        -- For v1, we extract from silver.edgar.form10_filings_rss if available
        -- This will need enhancement with SEC company submissions data
        select distinct
          cik,
          cast(null as int) as sic  -- placeholder until we have submissions data
        from silver.edgar.form10_filings_rss
      )
      select
        en.cik,
        en.entity_name,
        sc.sic,
        case 
          when sc.sic >= 6000 and sc.sic < 7000 then true
          else false
        end as is_financial,
        case
          when sc.sic >= 6000 and sc.sic < 6100 then 'depository'
          when sc.sic >= 6100 and sc.sic < 6200 then 'nondepository_credit'
          when sc.sic >= 6200 and sc.sic < 6300 then 'securities_commodities'
          when sc.sic >= 6300 and sc.sic < 6400 then 'insurance_carriers'
          when sc.sic >= 6400 and sc.sic < 6500 then 'insurance_agents'
          when sc.sic >= 6500 and sc.sic < 6600 then 'real_estate'
          when sc.sic >= 6700 and sc.sic < 7000 then 'holding_investment'
          else null
        end as financial_class
      from entity_names en
      left join sic_codes sc on en.cik = sc.cik

consumer:
  variant: MergeTable
  parameters:
    table: gold.dim.company
    key_columns: [cik]
